# Generated by Django 4.2.7 on 2025-09-18 11:10

import apps.customers.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.CharField(default=apps.customers.models.generate_card_id, max_length=50, primary_key=True, serialize=False)),
                ('last4', models.CharField(max_length=4)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('FROZEN', 'Frozen'), ('BLOCKED', 'Blocked'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=20)),
                ('network', models.CharField(choices=[('VISA', 'Visa'), ('MASTERCARD', 'Mastercard'), ('AMEX', 'American Express'), ('RUPAY', 'RuPay')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cards',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.CharField(default=apps.customers.models.generate_customer_id, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email_masked', models.CharField(max_length=255)),
                ('risk_flags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.CharField(default=apps.customers.models.generate_device_id, max_length=50, primary_key=True, serialize=False)),
                ('device_type', models.CharField(default='mobile', max_length=50)),
                ('device_fingerprint', models.CharField(blank=True, max_length=255)),
                ('is_trusted', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='customers.customer')),
            ],
            options={
                'db_table': 'devices',
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['email_masked'], name='customers_email_m_99201d_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['created_at'], name='customers_created_c63477_idx'),
        ),
        migrations.AddField(
            model_name='card',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='customers.customer'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['customer', 'is_trusted'], name='devices_custome_257400_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['last_seen'], name='devices_last_se_cc30d3_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['customer', 'status'], name='cards_custome_1f4f0c_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['last4'], name='cards_last4_6a29b8_idx'),
        ),
    ]
