# Generated by Django 4.2.7 on 2025-09-18 11:10

import apps.insights.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpendCategory',
            fields=[
                ('mcc', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'spend_categories',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeBaseDocument',
            fields=[
                ('id', models.CharField(default=apps.insights.models.generate_kb_id, max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('anchor', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('chunks', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'kb_documents',
                'indexes': [models.Index(fields=['title'], name='kb_document_title_f60617_idx'), models.Index(fields=['anchor'], name='kb_document_anchor_f50784_idx')],
            },
        ),
        migrations.CreateModel(
            name='InsightReport',
            fields=[
                ('id', models.CharField(default=apps.insights.models.generate_insight_id, max_length=50, primary_key=True, serialize=False)),
                ('report_type', models.CharField(max_length=50)),
                ('data', models.JSONField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='customers.customer')),
            ],
            options={
                'db_table': 'insight_reports',
                'indexes': [models.Index(fields=['customer', 'report_type'], name='insight_rep_custome_6e636c_idx'), models.Index(fields=['generated_at'], name='insight_rep_generat_cafab6_idx')],
            },
        ),
    ]
