# Generated by Django 4.2.7 on 2025-09-18 11:10

import apps.transactions.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.CharField(default=apps.transactions.models.generate_transaction_id, max_length=50, primary_key=True, serialize=False)),
                ('mcc', models.CharField(max_length=10)),
                ('merchant', models.CharField(max_length=255)),
                ('amount', models.BigIntegerField()),
                ('currency', models.CharField(choices=[('INR', 'Indian Rupee'), ('USD', 'US Dollar'), ('EUR', 'Euro')], default='INR', max_length=3)),
                ('timestamp', models.DateTimeField()),
                ('geo_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('geo_lon', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('geo_country', models.CharField(default='IN', max_length=3)),
                ('status', models.CharField(default='COMPLETED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='customers.card')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='customers.customer')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.device')),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Chargeback',
            fields=[
                ('id', models.CharField(default=apps.transactions.models.generate_chargeback_id, max_length=50, primary_key=True, serialize=False)),
                ('reason_code', models.CharField(max_length=10)),
                ('amount', models.BigIntegerField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('RESOLVED', 'Resolved'), ('REJECTED', 'Rejected')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chargebacks', to='customers.customer')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chargebacks', to='transactions.transaction')),
            ],
            options={
                'db_table': 'chargebacks',
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['customer', '-timestamp'], name='transaction_custome_4d2eb1_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['merchant'], name='transaction_merchan_43b14d_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['mcc'], name='transaction_mcc_1195b5_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['timestamp'], name='transaction_timesta_07633a_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['device'], name='transaction_device__e1fce0_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['geo_country'], name='transaction_geo_cou_bbf61c_idx'),
        ),
        migrations.AddIndex(
            model_name='chargeback',
            index=models.Index(fields=['customer', 'status'], name='chargebacks_custome_e8f7c5_idx'),
        ),
        migrations.AddIndex(
            model_name='chargeback',
            index=models.Index(fields=['created_at'], name='chargebacks_created_4666e5_idx'),
        ),
    ]
