# Generated by Django 4.2.7 on 2025-09-18 11:10

import apps.agents.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentExecution',
            fields=[
                ('id', models.CharField(default=apps.agents.models.generate_execution_id, max_length=50, primary_key=True, serialize=False)),
                ('execution_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('TIMEOUT', 'Timeout')], default='PENDING', max_length=20)),
                ('plan', models.JSONField(blank=True, default=list)),
                ('trace', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_executions', to='customers.customer')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.transaction')),
            ],
            options={
                'db_table': 'agent_executions',
            },
        ),
        migrations.CreateModel(
            name='ToolCall',
            fields=[
                ('id', models.CharField(default=apps.agents.models.generate_tool_call_id, max_length=50, primary_key=True, serialize=False)),
                ('tool_name', models.CharField(max_length=100)),
                ('input_data', models.JSONField(blank=True, default=dict)),
                ('output_data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('ERROR', 'Error'), ('TIMEOUT', 'Timeout')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_calls', to='agents.agentexecution')),
            ],
            options={
                'db_table': 'tool_calls',
                'indexes': [models.Index(fields=['execution', 'tool_name'], name='tool_calls_executi_8ea038_idx'), models.Index(fields=['status'], name='tool_calls_status_4c51ac_idx'), models.Index(fields=['started_at'], name='tool_calls_started_1219f4_idx')],
            },
        ),
        migrations.CreateModel(
            name='AgentFallback',
            fields=[
                ('id', models.CharField(default=apps.agents.models.generate_fallback_id, max_length=50, primary_key=True, serialize=False)),
                ('tool_name', models.CharField(max_length=100)),
                ('fallback_reason', models.CharField(max_length=255)),
                ('fallback_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fallbacks', to='agents.agentexecution')),
            ],
            options={
                'db_table': 'agent_fallbacks',
                'indexes': [models.Index(fields=['execution', 'tool_name'], name='agent_fallb_executi_f599b4_idx'), models.Index(fields=['created_at'], name='agent_fallb_created_12da48_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='agentexecution',
            index=models.Index(fields=['customer', 'status'], name='agent_execu_custome_39410c_idx'),
        ),
        migrations.AddIndex(
            model_name='agentexecution',
            index=models.Index(fields=['started_at'], name='agent_execu_started_520d3e_idx'),
        ),
        migrations.AddIndex(
            model_name='agentexecution',
            index=models.Index(fields=['execution_type'], name='agent_execu_executi_0e8c7c_idx'),
        ),
    ]
