# Generated by Django 4.2.7 on 2025-09-18 11:10

import apps.actions.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.CharField(default=apps.actions.models.generate_action_id, max_length=50, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('FREEZE_CARD', 'Freeze Card'), ('UNFREEZE_CARD', 'Unfreeze Card'), ('OPEN_DISPUTE', 'Open Dispute'), ('CONTACT_CUSTOMER', 'Contact Customer'), ('ESCALATE_CASE', 'Escalate Case')], max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PENDING_OTP', 'Pending OTP'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('BLOCKED', 'Blocked')], default='PENDING', max_length=20)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('otp_required', models.BooleanField(default=False)),
                ('otp_provided', models.CharField(blank=True, max_length=10)),
                ('otp_verified', models.BooleanField(default=False)),
                ('policy_blocked', models.BooleanField(default=False)),
                ('policy_reason', models.CharField(blank=True, max_length=255)),
                ('created_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.card')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='customers.customer')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.transaction')),
            ],
            options={
                'db_table': 'actions',
            },
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.CharField(default=apps.actions.models.generate_dispute_id, max_length=50, primary_key=True, serialize=False)),
                ('case_id', models.CharField(max_length=50, unique=True)),
                ('reason_code', models.CharField(max_length=10)),
                ('amount', models.BigIntegerField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('REJECTED', 'Rejected')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('action', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispute', to='actions.action')),
            ],
            options={
                'db_table': 'disputes',
                'indexes': [models.Index(fields=['case_id'], name='disputes_case_id_d2a079_idx'), models.Index(fields=['status'], name='disputes_status_811094_idx'), models.Index(fields=['created_at'], name='disputes_created_263e71_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='action',
            index=models.Index(fields=['customer', 'status'], name='actions_custome_6df4ee_idx'),
        ),
        migrations.AddIndex(
            model_name='action',
            index=models.Index(fields=['action_type', 'status'], name='actions_action__f544ae_idx'),
        ),
        migrations.AddIndex(
            model_name='action',
            index=models.Index(fields=['created_at'], name='actions_created_287a8a_idx'),
        ),
    ]
