# Generated by Django 4.2.7 on 2025-09-18 11:10

import apps.observability.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RateLimitLog',
            fields=[
                ('id', models.CharField(default=apps.observability.models.generate_ratelimit_id, max_length=50, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('endpoint', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('blocked_at', models.DateTimeField(auto_now_add=True)),
                ('retry_after_ms', models.IntegerField()),
            ],
            options={
                'db_table': 'rate_limit_logs',
                'indexes': [models.Index(fields=['user_id', 'blocked_at'], name='rate_limit__user_id_8714e9_idx'), models.Index(fields=['ip_address', 'blocked_at'], name='rate_limit__ip_addr_643386_idx')],
            },
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.CharField(default=apps.observability.models.generate_metric_id, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('metric_type', models.CharField(choices=[('COUNTER', 'Counter'), ('GAUGE', 'Gauge'), ('HISTOGRAM', 'Histogram')], max_length=20)),
                ('value', models.FloatField()),
                ('labels', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'metrics',
                'indexes': [models.Index(fields=['name', 'timestamp'], name='metrics_name_8083e4_idx'), models.Index(fields=['metric_type'], name='metrics_metric__b37976_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.CharField(default=apps.observability.models.generate_audit_id, max_length=50, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('ACTION_CREATED', 'Action Created'), ('ACTION_COMPLETED', 'Action Completed'), ('ACTION_BLOCKED', 'Action Blocked'), ('PII_ACCESSED', 'PII Accessed'), ('RATE_LIMITED', 'Rate Limited')], max_length=50)),
                ('user_id', models.CharField(blank=True, max_length=100)),
                ('customer_id', models.CharField(blank=True, max_length=50)),
                ('request_id', models.CharField(blank=True, max_length=100)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'audit_logs',
                'indexes': [models.Index(fields=['event_type', 'timestamp'], name='audit_logs_event_t_222f56_idx'), models.Index(fields=['user_id', 'timestamp'], name='audit_logs_user_id_88267f_idx'), models.Index(fields=['customer_id', 'timestamp'], name='audit_logs_custome_c7aee8_idx'), models.Index(fields=['request_id'], name='audit_logs_request_298ea7_idx')],
            },
        ),
    ]
